backend:
  name: git-gateway
  repo: cartoonfullmovie/cartoon-full-movie
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
- name: "posts"

    label: "المقالات"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "العنوان", name: "title", widget: "string"}

    - {label: "تاريخ النشر", name: "date", widget: "datetime"}

    - {label: "صورة الغلاف", name: "image", widget: "image"}

    - {label: "محتوى المقال", name: "body", widget: "markdown"}

